### ISSUE TITLE
gvLayout() failed

### ISSUE THREAD

**Issue by bingozhu0197** [schulmar/Templar#10]
I compiled in 5.8.0 succeed, but failed with "gvLayout() failed" in executing. Do you have any advice how to debug this?

**Comment by schulmar** [comment]
I have very little experience with graphviz. The error message obviously comes from qgraph.cpp
Which graphviz version and OS are you using? Is there any output on stderr? (Graphviz should print its errors there.)

**Comment by bingozhu0197** [comment]
Thanks for the reply. I am using windows7, 64-bit. This first happens in Graphviz2.38 when I click next arrow.  So I rollback to 2.34. But still exist. I will try to dig more today. Thanks all the same.

**Comment by bingozhu0197** [comment]
It works now. I added path "Graphviz2.34\lib\debug\dll" in build and clear it in system path env. Thanks

**Comment by schulmar** [comment]
So if I understood you correctly the problem comes with Graphviz 2.38?

**Comment by bingozhu0197** [comment]
It seems my PC env(path configuration problem) problem, not related with Graphviz version.

**Comment by schulmar** [comment]
Okay, thanks for clarifying.
