### ISSUE TITLE
Shortcut for Go to parent

### ISSUE THREAD

**Issue by wichtounet** [schulmar/Templar#7]
Hi, 

Just a small request that would greatly improve quality of life:  When you navigate large graphs, it is sometimes quite hard to find the go to parent node. It would be great if there was a button in the button bar to go to the parent directly.  

Thanks

**Comment by schulmar** [comment]
As you can see in the referenced commit, I added an "Up" button in the top row which will move up to the parent. This button has the shortcut key F7.

I'd like to hear if that is the desired feature or whether I missed something.

**Comment by wichtounet** [comment]
I just tested the new branch and the feature is perfect. This is exactly what I was thinking of :) This will save me a lot of time. 

Thanks.
