### ISSUE TITLE
Mutliline tooltip for the table

### ISSUE THREAD

**Issue by wichtounet** [schulmar/Templar#8]
Hi, 

In the trace I'm working with some names are insanely long (thousand of chars I guess). The tooltip in the table is quite practical for most names, but once the name is long the tooltip is larger than my two screens together. It would be great if the tooltip were multiline with some word wrapping. 

Thanks

**Comment by schulmar** [comment]
The referenced commit adds breaking of longer lines in the tooltip. In the long run it would probably be better to use some kind of formatter to improve readability.

**Comment by wichtounet** [comment]
Works like a charm :)

Some formatting would probably be good too, but this won't be trivial considering the complexity of C++ templates. This is already a good QoL improvement. Thanks.
